version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo starting sam package/deploy...
  build:
    commands:
      - echo starting sam package...
      - sam package --template-file template.yaml --s3-bucket salesforce-cti-adapter --output-template-file packaged-template.yaml
      - echo sam package is ready...
      - echo starting sam deploy...
      - sam deploy --template-file packaged-template.yaml --stack-name salesforce-cti-adapter --capabilities CAPABILITY_IAM --region us-east-1
  post_build:
    commands:
      - echo deployment completed on `date`
artifacts:
  files:
    - packaged-template.yml
